numprocs=40

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py

Start time:  2021-06-22 01:39:34.610684
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py

Creating network of 61 cell populations on 40 hosts...
  Number of cells on node 27: 289 
  Number of cells on node 0: 290 
  Done; cell creation time = 12.14 s.
Making connections...
  Number of cells on node 18: 289 
  Number of cells on node 33: 289 
  Number of cells on node 6: 290 
  Number of cells on node 9: 289 
  Number of cells on node 36: 289 
  Number of cells on node 20: 289 
  Number of cells on node 32: 289 
  Number of cells on node 28: 289 
  Number of cells on node 12: 289 
  Number of cells on node 4: 290 
  Number of cells on node 7: 290 
  Number of cells on node 24: 289 
  Number of cells on node 2: 290 
  Number of cells on node 16: 289 
  Number of cells on node 37: 289 
  Number of cells on node 5: 290 
  Number of cells on node 8: 289 
  Number of cells on node 13: 289 
  Number of cells on node 1: 290 
  Number of cells on node 19: 289 
  Number of cells on node 15: 289 
  Number of cells on node 3: 290 
  Number of cells on node 29: 289 
  Number of cells on node 17: 289 
  Number of cells on node 39: 289 
  Number of cells on node 30: 289 
  Number of cells on node 25: 289 
  Number of cells on node 21: 289 
  Number of cells on node 22: 289 
  Number of cells on node 11: 289 
  Number of cells on node 10: 289 
  Number of cells on node 23: 289 
  Number of cells on node 38: 289 
  Number of cells on node 14: 289 
  Number of cells on node 26: 289 
  Number of cells on node 31: 289 
  Number of cells on node 35: 289 
  Number of cells on node 34: 289 
  Number of connections on node 28: 1849 
  Number of synaptic contacts on node 28: 27670 
  Number of connections on node 20: 1819 
  Number of synaptic contacts on node 20: 26360 
  Number of connections on node 24: 1793 
  Number of synaptic contacts on node 24: 26000 
  Number of connections on node 8: 1915 
  Number of synaptic contacts on node 8: 27380 
  Number of connections on node 12: 1885 
  Number of synaptic contacts on node 12: 27150 
  Number of connections on node 18: 1843 
  Number of synaptic contacts on node 18: 26030 
  Number of connections on node 16: 1923 
  Number of synaptic contacts on node 16: 27780 
  Number of connections on node 38: 1860 
  Number of synaptic contacts on node 38: 26990 
  Number of connections on node 0: 1739 
  Number of synaptic contacts on node 0: 25310 
  Number of connections on node 2: 1810 
  Number of synaptic contacts on node 2: 26420 
  Number of connections on node 22: 1848 
  Number of synaptic contacts on node 22: 26720 
  Number of connections on node 3: 1820 
  Number of synaptic contacts on node 3: 26140 
  Number of connections on node 31: 1821 
  Number of synaptic contacts on node 31: 26380 
  Number of connections on node 32: 1776 
  Number of synaptic contacts on node 32: 26320 
  Number of connections on node 10: 1937 
  Number of synaptic contacts on node 10: 27730 
  Number of connections on node 26: 1924 
  Number of synaptic contacts on node 26: 27300 
  Number of connections on node 30: 1833 
  Number of synaptic contacts on node 30: 26490 
  Number of connections on node 4: 1938 
  Number of synaptic contacts on node 4: 28450 
  Number of connections on node 14: 2001 
  Number of synaptic contacts on node 14: 28920 
  Number of connections on node 15: 1942 
  Number of synaptic contacts on node 15: 27640 
  Number of connections on node 34: 1859 
  Number of synaptic contacts on node 34: 27530 
  Number of connections on node 5: 1739 
  Number of synaptic contacts on node 5: 24720 
  Number of connections on node 6: 1838 
  Number of synaptic contacts on node 6: 26590 
  Number of connections on node 19: 1767 
  Number of synaptic contacts on node 19: 25310 
  Number of connections on node 13: 1829 
  Number of synaptic contacts on node 13: 26270 
  Number of connections on node 36: 1789 
  Number of synaptic contacts on node 36: 26010 
  Number of connections on node 21: 1837 
  Number of synaptic contacts on node 21: 27140 
  Number of connections on node 1: 1718 
  Number of synaptic contacts on node 1: 24560 
  Number of connections on node 17: 1770 
  Number of synaptic contacts on node 17: 26470 
  Number of connections on node 29: 1857 
  Number of synaptic contacts on node 29: 26870 
  Number of connections on node 39: 1754 
  Number of synaptic contacts on node 39: 25690 
  Number of connections on node 27: 1888 
  Number of synaptic contacts on node 27: 26640 
  Number of connections on node 25: 1891 
  Number of synaptic contacts on node 25: 27250 
  Number of connections on node 33: 1894 
  Number of synaptic contacts on node 33: 27580 
  Number of connections on node 37: 1760 
  Number of synaptic contacts on node 37: 25440 
  Number of connections on node 9: 1814 
  Number of synaptic contacts on node 9: 26160 
  Number of connections on node 35: 1901 
  Number of synaptic contacts on node 35: 27050 
  Number of connections on node 11: 1951 
  Number of synaptic contacts on node 11: 28380 
  Number of connections on node 7: 1901 
  Number of synaptic contacts on node 7: 26530 
  Number of connections on node 23: 1901 
  Number of synaptic contacts on node 23: 27310 
  Done; cell connection time = 42.52 s.
Adding stims...
  Number of stims on node 12: 54 
  Number of stims on node 25: 54 
  Number of stims on node 5: 55 
  Number of stims on node 37: 55 
  Number of stims on node 13: 54 
  Number of stims on node 28: 55 
  Number of stims on node 31: 55 
  Number of stims on node 15: 54 
  Number of stims on node 8: 54 
  Number of stims on node 30: 55 
  Number of stims on node 11: 54 
  Number of stims on node 20: 54 
  Number of stims on node 23: 54 
  Number of stims on node 18: 54 
  Number of stims on node 33: 55 
  Number of stims on node 34: 55 
  Number of stims on node 24: 54 
  Number of stims on node 19: 54 
  Number of stims on node 21: 54 
  Number of stims on node 6: 55 
  Number of stims on node 14: 54 
  Number of stims on node 22: 54 
  Number of stims on node 17: 54 
  Number of stims on node 29: 55 
  Number of stims on node 26: 54 
  Number of stims on node 27: 54 
  Number of stims on node 36: 55 
  Number of stims on node 2: 55 
  Number of stims on node 0: 55 
  Number of stims on node 35: 55 
  Number of stims on node 32: 55 
  Number of stims on node 7: 55 
  Number of stims on node 16: 54 
  Number of stims on node 4: 55 
  Number of stims on node 10: 54 
  Number of stims on node 3: 55 
  Number of stims on node 39: 55 
  Number of stims on node 38: 55 
  Number of stims on node 1: 55 
  Number of stims on node 9: 54 
  Done; cell stims creation time = 0.31 s.
Recording 17 traces of 1 types on node 21
Recording 18 traces of 1 types on node 37
Recording 19 traces of 1 types on node 3
Recording 20 traces of 1 types on node 6
Recording 21 traces of 1 types on node 10
Recording 20 traces of 1 types on node 8
Recording 22 traces of 1 types on node 38
Recording 19 traces of 1 types on node 34
Recording 14 traces of 1 types on node 28
Recording 18 traces of 1 types on node 22
Recording 15 traces of 1 types on node 17
Recording 15 traces of 1 types on node 30
Recording 15 traces of 1 types on node 18
Recording 17 traces of 1 types on node 20
Recording 21 traces of 1 types on node 12
Recording 16 traces of 1 types on node 14
Recording 13 traces of 1 types on node 26
Recording 16 traces of 1 types on node 32
Recording 16 traces of 1 types on node 16
Recording 22 traces of 1 types on node 4
Recording 20 traces of 1 types on node 9
Recording 14 traces of 1 types on node 23
Recording 16 traces of 1 types on node 0
Recording 15 traces of 1 types on node 24
Recording 17 traces of 1 types on node 15
Recording 19 traces of 1 types on node 2
Recording 15 traces of 1 types on node 27
Recording 18 traces of 1 types on node 36
Recording 16 traces of 1 types on node 31
Recording 18 traces of 1 types on node 1
Recording 20 traces of 1 types on node 5
Recording 21 traces of 1 types on node 11
Recording 18 traces of 1 types on node 33
Recording 14 traces of 1 types on node 19
Recording 15 traces of 1 types on node 39
Recording 24 traces of 1 types on node 7
Recording 21 traces of 1 types on node 35
Recording 14 traces of 1 types on node 25
Recording 14 traces of 1 types on node 29
Recording 22 traces of 1 types on node 13
0.0s

Running simulation for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 5199.78 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 1.47 s.

Analyzing...
  Cells: 11568
  Connections: 0 (0.00 per cell)
  Spikes: 79662 (3.44 Hz)
  Simulated time: 2.0 s; 40 workers
  Run time: 5199.78 s
   L1_DAC : 0.000 Hz
   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.000 Hz
   L1_NGC-SA : 0.000 Hz
   L1_SLAC : 0.000 Hz
   L23_BP : 0.000 Hz
   L23_BTC : 0.000 Hz
   L23_ChC : 0.000 Hz
   L23_DBC : 0.000 Hz
   L23_LBC : 0.000 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.000 Hz
   L23_NGC : 0.000 Hz
   L23_PC : 0.000 Hz
   L23_SBC : 0.000 Hz
   L4_BP : 0.000 Hz
   L4_BTC : 0.000 Hz
   L4_ChC : 0.000 Hz
   L4_DBC : 0.000 Hz
   L4_LBC : 0.000 Hz
   L4_MC : 0.000 Hz
   L4_NBC : 0.000 Hz
   L4_NGC : 0.000 Hz
   L4_PC : 0.000 Hz
   L4_SBC : 0.000 Hz
   L4_SP : 0.000 Hz
   L4_SS : 0.000 Hz
   L5_BP : 0.000 Hz
   L5_BTC : 0.000 Hz
   L5_ChC : 0.000 Hz
   L5_DBC : 0.000 Hz
   L5_LBC : 0.000 Hz
   L5_MC : 0.000 Hz
   L5_NBC : 0.000 Hz
   L5_NGC : 0.000 Hz
   L5_SBC : 0.000 Hz
   L5_STPC : 0.000 Hz
   L5_TTPC1 : 0.000 Hz
   L5_TTPC2 : 0.000 Hz
   L5_UTPC : 0.000 Hz
   L6_BPC : 0.000 Hz
   L6_BP : 0.000 Hz
   L6_BTC : 0.000 Hz
   L6_ChC : 0.000 Hz
   L6_DBC : 0.000 Hz
   L6_IPC : 0.000 Hz
   L6_LBC : 0.000 Hz
   L6_MC : 0.000 Hz
   L6_NBC : 0.000 Hz
   L6_NGC : 0.000 Hz
   L6_SBC : 0.000 Hz
   L6_TPC_L1 : 0.000 Hz
   L6_TPC_L4 : 0.000 Hz
   L6_UTPC : 0.000 Hz
   ss_RTN_o : 15.334 Hz
   ss_RTN_m : 16.813 Hz
   ss_RTN_i : 16.003 Hz
   VPL_sTC : 6.933 Hz
   VPM_sTC : 5.265 Hz
   POm_sTC_s1 : 9.260 Hz
Saving output as ../data/v1_batch4/v1_batch4_0.json  ... 
Finished saving!
  Done; saving time = 0.05 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 167.04 s

Total time = 5433.45 s

End time:  2021-06-22 03:10:08.058870
