numprocs=60

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py

Start time:  2021-06-22 15:42:32.014948
Importing netParams from ../data/v1_batch5/v1_batch5_netParams.py

Creating network of 61 cell populations on 60 hosts...
  Number of cells on node 53: 192 
  Number of cells on node 18: 193 
  Number of cells on node 50: 192 
  Number of cells on node 28: 193 
  Number of cells on node 3: 193 
  Number of cells on node 25: 193 
  Number of cells on node 19: 193 
  Number of cells on node 55: 192 
  Number of cells on node 37: 193 
  Number of cells on node 41: 193 
  Number of cells on node 8: 193 
  Number of cells on node 34: 193 
  Number of cells on node 31: 193 
  Number of cells on node 10: 193 
  Number of cells on node 43: 193 
  Number of cells on node 2: 193 
  Number of cells on node 52: 192 
  Number of cells on node 7: 193 
  Number of cells on node 59: 192 
  Number of cells on node 24: 193 
  Number of cells on node 15: 193 
  Number of cells on node 12: 193 
  Number of cells on node 17: 193 
  Number of cells on node 56: 192 
  Number of cells on node 47: 193 
  Number of cells on node 49: 192 
  Number of cells on node 14: 193 
  Number of cells on node 20: 193 
  Number of cells on node 4: 193 
  Number of cells on node 45: 193 
  Number of cells on node 30: 193 
  Number of cells on node 21: 193 
  Number of cells on node 36: 193 
  Number of cells on node 26: 193 
  Number of cells on node 33: 193 
  Number of cells on node 51: 192 
  Number of cells on node 1: 193 
  Number of cells on node 44: 193 
  Number of cells on node 6: 193 
  Number of cells on node 13: 193 
  Number of cells on node 57: 192 
  Number of cells on node 35: 193 
  Number of cells on node 16: 193 
  Number of cells on node 39: 193 
  Number of cells on node 5: 193 
  Number of cells on node 38: 193 
  Number of cells on node 9: 193 
  Number of cells on node 22: 193 
  Number of cells on node 27: 193 
  Number of cells on node 29: 193 
  Number of cells on node 0: 193 
  Done; cell creation time = 15.46 s.
Making connections...
  Number of cells on node 46: 193 
  Number of cells on node 54: 192 
  Number of cells on node 40: 193 
  Number of cells on node 48: 192 
  Number of cells on node 23: 193 
  Number of cells on node 58: 192 
  Number of cells on node 42: 193 
  Number of cells on node 11: 193 
  Number of cells on node 32: 193 
  Number of connections on node 48: 14080 
  Number of synaptic contacts on node 48: 145588 
  Number of connections on node 10: 14090 
  Number of synaptic contacts on node 10: 144386 
  Number of connections on node 21: 13892 
  Number of synaptic contacts on node 21: 144824 
  Number of connections on node 33: 14043 
  Number of synaptic contacts on node 33: 146276 
  Number of connections on node 29: 14292 
  Number of synaptic contacts on node 29: 150968 
  Number of connections on node 30: 14530 
  Number of synaptic contacts on node 30: 154230 
  Number of connections on node 58: 14245 
  Number of synaptic contacts on node 58: 147218 
  Number of connections on node 42: 14077 
  Number of synaptic contacts on node 42: 144374 
  Number of connections on node 53: 14362 
  Number of synaptic contacts on node 53: 149848 
  Number of connections on node 32: 14096 
  Number of synaptic contacts on node 32: 146408 
  Number of connections on node 34: 13818 
  Number of synaptic contacts on node 34: 143396 
  Number of connections on node 41: 13799 
  Number of synaptic contacts on node 41: 141680 
  Number of connections on node 56: 13859 
  Number of synaptic contacts on node 56: 142634 
  Number of connections on node 39: 13814 
  Number of synaptic contacts on node 39: 141618 
  Number of connections on node 6: 14104 
  Number of synaptic contacts on node 6: 145068 
  Number of connections on node 36: 14013 
  Number of synaptic contacts on node 36: 142532 
  Number of connections on node 15: 14006 
  Number of synaptic contacts on node 15: 146404 
  Number of connections on node 19: 14079 
  Number of synaptic contacts on node 19: 148452 
  Number of connections on node 45: 14045 
  Number of synaptic contacts on node 45: 143984 
  Number of connections on node 9: 14239 
  Number of synaptic contacts on node 9: 148600 
  Number of connections on node 16: 14349 
  Number of synaptic contacts on node 16: 149536 
  Number of connections on node 43: 13797 
  Number of synaptic contacts on node 43: 143578 
  Number of connections on node 52: 14138 
  Number of synaptic contacts on node 52: 146338 
  Number of connections on node 46: 14035 
  Number of synaptic contacts on node 46: 144480 
  Number of connections on node 57: 13873 
  Number of synaptic contacts on node 57: 143010 
  Number of connections on node 12: 13875 
  Number of synaptic contacts on node 12: 143552 
  Number of connections on node 35: 13746 
  Number of synaptic contacts on node 35: 141866 
  Number of connections on node 17: 14410 
  Number of synaptic contacts on node 17: 151136 
  Number of connections on node 1: 14519 
  Number of synaptic contacts on node 1: 149516 
  Number of connections on node 22: 14114 
  Number of synaptic contacts on node 22: 148200 
  Number of connections on node 5: 14080 
  Number of synaptic contacts on node 5: 145276 
  Number of connections on node 59: 14070 
  Number of synaptic contacts on node 59: 145694 
  Number of connections on node 24: 14146 
  Number of synaptic contacts on node 24: 148478 
  Number of connections on node 11: 14390 
  Number of synaptic contacts on node 11: 147846 
  Number of connections on node 37: 14477 
  Number of synaptic contacts on node 37: 148188 
  Number of connections on node 51: 14289 
  Number of synaptic contacts on node 51: 147664 
  Number of connections on node 31: 14270 
  Number of synaptic contacts on node 31: 149352 
  Number of connections on node 3: 14240 
  Number of synaptic contacts on node 3: 148760 
  Number of connections on node 55: 13742 
  Number of synaptic contacts on node 55: 142588 
  Number of connections on node 18: 14252 
  Number of synaptic contacts on node 18: 149076 
  Number of connections on node 7: 14208 
  Number of synaptic contacts on node 7: 146576 
  Number of connections on node 47: 14836 
  Number of synaptic contacts on node 47: 152656 
  Number of connections on node 27: 13857 
  Number of synaptic contacts on node 27: 144342 
  Number of connections on node 25: 14053 
  Number of synaptic contacts on node 25: 146544 
  Number of connections on node 26: 14092 
  Number of synaptic contacts on node 26: 147592 
  Number of connections on node 23: 13998 
  Number of synaptic contacts on node 23: 145814 
  Number of connections on node 40: 14054 
  Number of synaptic contacts on node 40: 145174 
  Number of connections on node 13: 14170 
  Number of synaptic contacts on node 13: 147908 
  Number of connections on node 54: 14056 
  Number of synaptic contacts on node 54: 145536 
  Number of connections on node 2: 13983 
  Number of synaptic contacts on node 2: 145794 
  Number of connections on node 8: 14173 
  Number of synaptic contacts on node 8: 146432 
  Number of connections on node 38: 14105 
  Number of synaptic contacts on node 38: 146078 
  Number of connections on node 14: 14294 
  Number of synaptic contacts on node 14: 150012 
  Number of connections on node 4: 13898 
  Number of synaptic contacts on node 4: 145296 
  Number of connections on node 28: 14427 
  Number of synaptic contacts on node 28: 151672 
  Number of connections on node 49: 14203 
  Number of synaptic contacts on node 49: 145956 
  Number of connections on node 0: 14414 
  Number of synaptic contacts on node 0: 148726 
  Number of connections on node 20: 14541 
  Number of synaptic contacts on node 20: 152202 
  Number of connections on node 50: 13910 
  Number of synaptic contacts on node 50: 144302 
  Number of connections on node 44: 14114 
  Number of synaptic contacts on node 44: 147618 
  Done; cell connection time = 1011.56 s.
Adding stims...
  Number of stims on node 46: 1347 
  Number of stims on node 5: 1346 
  Number of stims on node 56: 1346 
  Number of stims on node 53: 1346 
  Number of stims on node 54: 1346 
  Number of stims on node 55: 1346 
  Number of stims on node 35: 1347 
  Number of stims on node 44: 1347 
  Number of stims on node 47: 1347 
  Number of stims on node 0: 1346 
  Number of stims on node 39: 1347 
  Number of stims on node 1: 1346 
  Number of stims on node 19: 1346 
  Number of stims on node 20: 1346 
  Number of stims on node 23: 1346 
  Number of stims on node 45: 1347 
  Number of stims on node 16: 1346 
  Number of stims on node 22: 1346 
  Number of stims on node 34: 1347 
  Number of stims on node 14: 1346 
  Number of stims on node 8: 1346 
  Number of stims on node 10: 1346 
  Number of stims on node 15: 1346 
  Number of stims on node 12: 1346 
  Number of stims on node 6: 1346 
  Number of stims on node 26: 1346 
  Number of stims on node 48: 1346 
  Number of stims on node 32: 1347 
  Number of stims on node 4: 1346 
  Number of stims on node 7: 1346 
  Number of stims on node 52: 1346 
  Number of stims on node 3: 1346 
  Number of stims on node 36: 1347 
  Number of stims on node 38: 1347 
  Number of stims on node 42: 1347 
  Number of stims on node 43: 1347 
  Number of stims on node 21: 1346 
  Number of stims on node 28: 1347 
  Number of stims on node 18: 1346 
  Number of stims on node 58: 1346 
  Number of stims on node 31: 1347 
  Number of stims on node 13: 1346 
  Number of stims on node 37: 1347 
  Number of stims on node 25: 1346 
  Number of stims on node 11: 1346 
  Number of stims on node 29: 1347 
  Number of stims on node 57: 1346 
  Number of stims on node 51: 1346 
  Number of stims on node 30: 1347 
  Number of stims on node 41: 1347 
  Number of stims on node 59: 1336 
  Number of stims on node 24: 1346 
  Number of stims on node 33: 1347 
  Number of stims on node 27: 1346 
  Number of stims on node 2: 1346 
  Number of stims on node 40: 1347 
  Number of stims on node 9: 1346 
  Number of stims on node 50: 1346 
  Number of stims on node 17: 1346 
  Done; cell stims creation time = 3.79 s.
  Number of stims on node 49: 1346 
Recording 10 traces of 1 types on node 51
Recording 10 traces of 1 types on node 6
Recording 10 traces of 1 types on node 52
Recording 10 traces of 1 types on node 11
Recording 11 traces of 1 types on node 58
Recording 14 traces of 1 types on node 29
Recording 10 traces of 1 types on node 8
Recording 13 traces of 1 types on node 45
Recording 14 traces of 1 types on node 47
Recording 11 traces of 1 types on node 48
Recording 11 traces of 1 types on node 13
Recording 19 traces of 1 types on node 33
Recording 11 traces of 1 types on node 46
Recording 10 traces of 1 types on node 57
Recording 13 traces of 1 types on node 36
Recording 16 traces of 1 types on node 34
Recording 15 traces of 1 types on node 30
Recording 12 traces of 1 types on node 37
Recording 11 traces of 1 types on node 5
Recording 8 traces of 1 types on node 20
Recording 13 traces of 1 types on node 3
Recording 14 traces of 1 types on node 27
Recording 12 traces of 1 types on node 26
Recording 10 traces of 1 types on node 12
Recording 14 traces of 1 types on node 1
Recording 10 traces of 1 types on node 55
Recording 12 traces of 1 types on node 39
Recording 11 traces of 1 types on node 22
Recording 11 traces of 1 types on node 9
Recording 11 traces of 1 types on node 16
Recording 10 traces of 1 types on node 23
Recording 17 traces of 1 types on node 31
Recording 11 traces of 1 types on node 42
Recording 13 traces of 1 types on node 24
Recording 11 traces of 1 types on node 41
Recording 12 traces of 1 types on node 4
Recording 12 traces of 1 types on node 44
Recording 10 traces of 1 types on node 21
Recording 11 traces of 1 types on node 7
Recording 9 traces of 1 types on node 49
Recording 15 traces of 1 types on node 2
Recording 10 traces of 1 types on node 59
Recording 17 traces of 1 types on node 32
Recording 11 traces of 1 types on node 10
Recording 16 traces of 1 types on node 35
Recording 13 traces of 1 types on node 28
Recording 10 traces of 1 types on node 53
Recording 14 traces of 1 types on node 38
Recording 10 traces of 1 types on node 50
Recording 10 traces of 1 types on node 43
Recording 7 traces of 1 types on node 19
Recording 11 traces of 1 types on node 17
Recording 12 traces of 1 types on node 15
Recording 10 traces of 1 types on node 25
Recording 12 traces of 1 types on node 40
Recording 13 traces of 1 types on node 0
Recording 11 traces of 1 types on node 14
Recording 10 traces of 1 types on node 56
Recording 12 traces of 1 types on node 18
Recording 8 traces of 1 types on node 54
0.0s

Running simulation for 500.0 ms...
0.0s
0.0s
0.0s
0.0s
0.1s
0.1s
0.1s
0.1s
0.1s
0.1s
0.1s
0.1s
0.1s
0.1s
0.2s
0.2s
0.2s
0.2s
0.2s
0.2s
0.2s
0.2s
0.2s
0.2s
0.2s
0.3s
0.3s
0.3s
0.3s
0.3s
0.3s
0.3s
0.3s
0.3s
0.3s
0.4s
0.4s
0.4s
0.4s
0.4s
0.4s
0.4s
0.4s
0.4s
0.4s
0.5s
0.5s
0.5s
0.5s
0.5s
  Done; run time = 2137.23 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 3.45 s.

Analyzing...
  Cells: 11568
  Connections: 0 (0.00 per cell)
  Spikes: 33634 (5.82 Hz)
  Simulated time: 0.5 s; 60 workers
  Run time: 2137.23 s
   L1_DAC : 0.000 Hz
   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.000 Hz
   L1_NGC-SA : 0.000 Hz
   L1_SLAC : 0.300 Hz
   L23_BP : 0.000 Hz
   L23_BTC : 0.154 Hz
   L23_ChC : 0.750 Hz
   L23_DBC : 0.000 Hz
   L23_LBC : 0.667 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.646 Hz
   L23_NGC : 0.000 Hz
   L23_PC : 0.123 Hz
   L23_SBC : 0.683 Hz
   L4_BP : 0.000 Hz
   L4_BTC : 2.750 Hz
   L4_ChC : 0.000 Hz
   L4_DBC : 0.182 Hz
   L4_LBC : 2.703 Hz
   L4_MC : 0.118 Hz
   L4_NBC : 2.643 Hz
   L4_NGC : 2.000 Hz
   L4_PC : 0.712 Hz
   L4_SBC : 3.778 Hz
   L4_SP : 1.009 Hz
   L4_SS : 1.183 Hz
   L5_BP : 1.750 Hz
   L5_BTC : 2.000 Hz
   L5_ChC : 2.000 Hz
   L5_DBC : 0.917 Hz
   L5_LBC : 5.552 Hz
   L5_MC : 0.206 Hz
   L5_NBC : 6.857 Hz
   L5_NGC : 6.000 Hz
   L5_SBC : 4.333 Hz
   L5_STPC : 1.711 Hz
   L5_TTPC1 : 2.663 Hz
   L5_TTPC2 : 1.935 Hz
   L5_UTPC : 2.128 Hz
   L6_BPC : 1.953 Hz
   L6_BP : 5.429 Hz
   L6_BTC : 9.273 Hz
   L6_ChC : 21.333 Hz
   L6_DBC : 5.500 Hz
   L6_IPC : 2.767 Hz
   L6_LBC : 7.040 Hz
   L6_MC : 0.611 Hz
   L6_NBC : 7.238 Hz
   L6_NGC : 7.600 Hz
   L6_SBC : 9.714 Hz
   L6_TPC_L1 : 1.887 Hz
   L6_TPC_L4 : 2.660 Hz
   L6_UTPC : 2.787 Hz
   ss_RTN_o : 13.178 Hz
   ss_RTN_m : 18.675 Hz
   ss_RTN_i : 16.829 Hz
   VPL_sTC : 13.662 Hz
   VPM_sTC : 11.325 Hz
   POm_sTC_s1 : 15.422 Hz
Saving output as ../data/v1_batch5/v1_batch5_0.json  ... 
Finished saving!
  Done; saving time = 0.04 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 126.46 s

Total time = 3311.26 s

End time:  2021-06-22 16:37:43.273766
