INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
numprocs=110

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v0_batch4/v0_batch4_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py

Start time:  2021-04-11 14:58:41.916176
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py
Importing netParams from ../data/v0_batch4/v0_batch4_netParams.py

Creating network of 55 cell populations on 110 hosts...
  Number of cells on node 8: 72 
  Number of cells on node 13: 72 
  Number of cells on node 40: 72 
  Number of cells on node 78: 71 
  Number of cells on node 9: 72 
  Number of cells on node 30: 72 
  Number of cells on node 95: 71 
  Number of cells on node 38: 72 
  Number of cells on node 5: 72 
  Number of cells on node 47: 72 
  Number of cells on node 0: 72 
  Done; cell creation time = 9.01 s.
Making connections...
  Number of cells on node 94: 71 
  Number of cells on node 24: 72 
  Number of cells on node 2: 72 
  Number of cells on node 81: 71 
  Number of cells on node 46: 72 
  Number of cells on node 22: 72 
  Number of cells on node 88: 71 
  Number of cells on node 6: 72 
  Number of cells on node 77: 71 
  Number of cells on node 32: 72 
  Number of cells on node 89: 71 
  Number of cells on node 27: 72 
  Number of cells on node 108: 71 
  Number of cells on node 11: 72 
  Number of cells on node 62: 71 
  Number of cells on node 67: 71 
  Number of cells on node 102: 71 
  Number of cells on node 53: 71 
  Number of cells on node 15: 72 
  Number of cells on node 25: 72 
  Number of cells on node 50: 71 
  Number of cells on node 3: 72 
  Number of cells on node 29: 72 
  Number of cells on node 54: 71 
  Number of cells on node 87: 71 
  Number of cells on node 104: 71 
  Number of cells on node 37: 72 
  Number of cells on node 106: 71 
  Number of cells on node 93: 71 
  Number of cells on node 76: 71 
  Number of cells on node 17: 72 
  Number of cells on node 73: 71 
  Number of cells on node 65: 71 
  Number of cells on node 35: 72 
  Number of cells on node 100: 71 
  Number of cells on node 96: 71 
  Number of cells on node 83: 71 
  Number of cells on node 109: 71 
  Number of cells on node 98: 71 
  Number of cells on node 68: 71 
  Number of cells on node 23: 72 
  Number of cells on node 71: 71 
  Number of cells on node 99: 71 
  Number of cells on node 1: 72 
  Number of cells on node 20: 72 
  Number of cells on node 101: 71 
  Number of cells on node 26: 72 
  Number of cells on node 72: 71 
  Number of cells on node 49: 71 
  Number of cells on node 97: 71 
  Number of cells on node 85: 71 
  Number of cells on node 42: 72 
  Number of cells on node 91: 71 
  Number of cells on node 70: 71 
  Number of cells on node 61: 71 
  Number of cells on node 64: 71 
  Number of cells on node 33: 72 
  Number of cells on node 107: 71 
  Number of cells on node 21: 72 
  Number of cells on node 92: 71 
  Number of cells on node 36: 72 
  Number of cells on node 19: 72 
  Number of cells on node 4: 72 
  Number of cells on node 90: 71 
  Number of cells on node 60: 71 
  Number of cells on node 86: 71 
  Number of cells on node 18: 72 
  Number of cells on node 7: 72 
  Number of cells on node 84: 71 
  Number of cells on node 52: 71 
  Number of cells on node 48: 72 
  Number of cells on node 51: 71 
  Number of cells on node 69: 71 
  Number of cells on node 16: 72 
  Number of cells on node 55: 71 
  Number of cells on node 28: 72 
  Number of cells on node 43: 72 
  Number of cells on node 31: 72 
  Number of cells on node 10: 72 
  Number of cells on node 103: 71 
  Number of cells on node 39: 72 
  Number of cells on node 44: 72 
  Number of cells on node 34: 72 
  Number of cells on node 45: 72 
  Number of cells on node 59: 71 
  Number of cells on node 80: 71 
  Number of cells on node 66: 71 
  Number of cells on node 58: 71 
  Number of cells on node 12: 72 
  Number of cells on node 41: 72 
  Number of cells on node 75: 71 
  Number of cells on node 79: 71 
  Number of cells on node 82: 71 
  Number of cells on node 56: 71 
  Number of cells on node 14: 72 
  Number of cells on node 105: 71 
  Number of cells on node 74: 71 
  Number of cells on node 63: 71 
  Number of cells on node 57: 71 
  Number of connections on node 89: 6946 
  Number of synaptic contacts on node 89: 69610 
  Number of connections on node 77: 6954 
  Number of synaptic contacts on node 77: 68708 
  Number of connections on node 8: 6975 
  Number of synaptic contacts on node 8: 69906 
  Number of connections on node 91: 6820 
  Number of synaptic contacts on node 91: 68696 
  Number of connections on node 72: 6845 
  Number of synaptic contacts on node 72: 68632 
  Number of connections on node 52: 7083 
  Number of synaptic contacts on node 52: 70002 
  Number of connections on node 50: 7230 
  Number of synaptic contacts on node 50: 72196 
  Number of connections on node 0: 7187 
  Number of synaptic contacts on node 0: 72460 
  Number of connections on node 30: 7073 
  Number of synaptic contacts on node 30: 70774 
  Number of connections on node 86: 6726 
  Number of synaptic contacts on node 86: 67418 
  Number of connections on node 97: 7178 
  Number of synaptic contacts on node 97: 72750 
  Number of connections on node 45: 7394 
  Number of synaptic contacts on node 45: 72338 
  Number of connections on node 42: 7220 
  Number of synaptic contacts on node 42: 72502 
  Number of connections on node 20: 7206 
  Number of synaptic contacts on node 20: 71526 
  Number of connections on node 36: 7563 
  Number of synaptic contacts on node 36: 75532 
  Number of connections on node 7: 7185 
  Number of synaptic contacts on node 7: 70852 
  Number of connections on node 104: 6821 
  Number of synaptic contacts on node 104: 67478 
  Number of connections on node 74: 7013 
  Number of synaptic contacts on node 74: 70312 
  Number of connections on node 102: 6822 
  Number of synaptic contacts on node 102: 69562 
  Number of connections on node 70: 7405 
  Number of synaptic contacts on node 70: 73314 
  Number of connections on node 54: 6873 
  Number of synaptic contacts on node 54: 68288 
  Number of connections on node 80: 6811 
  Number of synaptic contacts on node 80: 68066 
  Number of connections on node 82: 6652 
  Number of synaptic contacts on node 82: 66406 
  Number of connections on node 68: 7307 
  Number of synaptic contacts on node 68: 73536 
  Number of connections on node 88: 6827 
  Number of synaptic contacts on node 88: 68198 
  Number of connections on node 16: 7278 
  Number of synaptic contacts on node 16: 72038 
  Number of connections on node 12: 7265 
  Number of synaptic contacts on node 12: 71734 
  Number of connections on node 46: 7174 
  Number of synaptic contacts on node 46: 71506 
  Number of connections on node 109: 7020 
  Number of synaptic contacts on node 109: 69360 
  Number of connections on node 62: 7312 
  Number of synaptic contacts on node 62: 72504 
  Number of connections on node 28: 6945 
  Number of synaptic contacts on node 28: 70108 
  Number of connections on node 11: 6923 
  Number of synaptic contacts on node 11: 68734 
  Number of connections on node 94: 7213 
  Number of synaptic contacts on node 94: 73244 
  Number of connections on node 106: 6714 
  Number of synaptic contacts on node 106: 66566 
  Number of connections on node 40: 7002 
  Number of synaptic contacts on node 40: 70768 
  Number of connections on node 95: 6820 
  Number of synaptic contacts on node 95: 68292 
  Number of connections on node 38: 7278 
  Number of synaptic contacts on node 38: 72336 
  Number of connections on node 17: 7113 
  Number of synaptic contacts on node 17: 70142 
  Number of connections on node 51: 7003 
  Number of synaptic contacts on node 51: 68158 
  Number of connections on node 18: 6936 
  Number of synaptic contacts on node 18: 67860 
  Number of connections on node 27: 7243 
  Number of synaptic contacts on node 27: 72298 
  Number of connections on node 100: 7425 
  Number of synaptic contacts on node 100: 74976 
  Number of connections on node 92: 7297 
  Number of synaptic contacts on node 92: 73418 
  Number of connections on node 39: 7292 
  Number of synaptic contacts on node 39: 72624 
  Number of connections on node 90: 7186 
  Number of synaptic contacts on node 90: 72118 
  Number of connections on node 75: 6843 
  Number of synaptic contacts on node 75: 69058 
  Number of connections on node 23: 7399 
  Number of synaptic contacts on node 23: 74006 
  Number of connections on node 67: 6888 
  Number of synaptic contacts on node 67: 68714 
  Number of connections on node 49: 6954 
  Number of synaptic contacts on node 49: 68764 
  Number of connections on node 84: 6917 
  Number of synaptic contacts on node 84: 69082 
  Number of connections on node 55: 7201 
  Number of synaptic contacts on node 55: 71092 
  Number of connections on node 85: 7231 
  Number of synaptic contacts on node 85: 72056 
  Number of connections on node 66: 6996 
  Number of synaptic contacts on node 66: 69572 
  Number of connections on node 26: 7178 
  Number of synaptic contacts on node 26: 72290 
  Number of connections on node 2: 7063 
  Number of synaptic contacts on node 2: 71074 
  Number of connections on node 65: 7004 
  Number of synaptic contacts on node 65: 69510 
  Number of connections on node 10: 7309 
  Number of synaptic contacts on node 10: 72578 
  Number of connections on node 6: 7098 
  Number of synaptic contacts on node 6: 70878 
  Number of connections on node 41: 7193 
  Number of synaptic contacts on node 41: 72784 
  Number of connections on node 56: 6770 
  Number of synaptic contacts on node 56: 66814 
  Number of connections on node 83: 7208 
  Number of synaptic contacts on node 83: 71274 
  Number of connections on node 24: 6807 
  Number of synaptic contacts on node 24: 68316 
  Number of connections on node 107: 7201 
  Number of synaptic contacts on node 107: 73884 
  Number of connections on node 93: 7041 
  Number of synaptic contacts on node 93: 71062 
  Number of connections on node 78: 6864 
  Number of synaptic contacts on node 78: 68132 
  Number of connections on node 103: 7002 
  Number of synaptic contacts on node 103: 70816 
  Number of connections on node 108: 7176 
  Number of synaptic contacts on node 108: 72456 
  Number of connections on node 96: 6698 
  Number of synaptic contacts on node 96: 67486 
  Number of connections on node 99: 6802 
  Number of synaptic contacts on node 99: 68962 
  Number of connections on node 35: 7027 
  Number of synaptic contacts on node 35: 70392 
  Number of connections on node 21: 7169 
  Number of synaptic contacts on node 21: 71708 
  Number of connections on node 43: 7112 
  Number of synaptic contacts on node 43: 71096 
  Number of connections on node 81: 7201 
  Number of synaptic contacts on node 81: 70664 
  Number of connections on node 9: 7185 
  Number of synaptic contacts on node 9: 70942 
  Number of connections on node 60: 6904 
  Number of synaptic contacts on node 60: 68728 
  Number of connections on node 71: 6887 
  Number of synaptic contacts on node 71: 69144 
  Number of connections on node 4: 7247 
  Number of synaptic contacts on node 4: 71646 
  Number of connections on node 1: 7086 
  Number of synaptic contacts on node 1: 70308 
  Number of connections on node 58: 6740 
  Number of synaptic contacts on node 58: 67752 
  Number of connections on node 73: 6706 
  Number of synaptic contacts on node 73: 66428 
  Number of connections on node 32: 7178 
  Number of synaptic contacts on node 32: 71198 
  Number of connections on node 31: 7197 
  Number of synaptic contacts on node 31: 72418 
  Number of connections on node 105: 6973 
  Number of synaptic contacts on node 105: 69830 
  Number of connections on node 48: 7011 
  Number of synaptic contacts on node 48: 69182 
  Number of connections on node 69: 7115 
  Number of synaptic contacts on node 69: 70362 
  Number of connections on node 13: 6838 
  Number of synaptic contacts on node 13: 68466 
  Number of connections on node 79: 6749 
  Number of synaptic contacts on node 79: 66362 
  Number of connections on node 15: 7191 
  Number of synaptic contacts on node 15: 71090 
  Number of connections on node 25: 7155 
  Number of synaptic contacts on node 25: 71022 
  Number of connections on node 101: 7055 
  Number of synaptic contacts on node 101: 70848 
  Number of connections on node 37: 6906 
  Number of synaptic contacts on node 37: 69180 
  Number of connections on node 61: 6968 
  Number of synaptic contacts on node 61: 69462 
  Number of connections on node 3: 7402 
  Number of synaptic contacts on node 3: 73288 
  Number of connections on node 47: 7414 
  Number of synaptic contacts on node 47: 73504 
  Number of connections on node 29: 7232 
  Number of synaptic contacts on node 29: 70490 
  Number of connections on node 64: 6933 
  Number of synaptic contacts on node 64: 68010 
  Number of connections on node 76: 6961 
  Number of synaptic contacts on node 76: 68790 
  Number of connections on node 33: 7041 
  Number of synaptic contacts on node 33: 72384 
  Number of connections on node 34: 7005 
  Number of synaptic contacts on node 34: 70582 
  Number of connections on node 98: 7032 
  Number of synaptic contacts on node 98: 70610 
  Number of connections on node 44: 7309 
  Number of synaptic contacts on node 44: 74336 
  Number of connections on node 87: 6476 
  Number of synaptic contacts on node 87: 65314 
  Number of connections on node 22: 7350 
  Number of synaptic contacts on node 22: 72226 
  Number of connections on node 14: 7269 
  Number of synaptic contacts on node 14: 72480 
  Number of connections on node 59: 7266 
  Number of synaptic contacts on node 59: 72276 
  Number of connections on node 57: 7174 
  Number of synaptic contacts on node 57: 71370 
  Number of connections on node 63: 7020 
  Number of synaptic contacts on node 63: 68008 
  Number of connections on node 19: 7022 
  Number of synaptic contacts on node 19: 70966 
  Number of connections on node 53: 7093 
  Number of synaptic contacts on node 53: 70060 
  Done; cell connection time = 1793.84 s.
  Number of connections on node 5: 7219 
  Number of synaptic contacts on node 5: 71866 
Adding stims...
  Number of stims on node 22: 720 
  Number of stims on node 97: 710 
  Number of stims on node 6: 720 
  Number of stims on node 45: 720 
  Number of stims on node 89: 710 
  Number of stims on node 1: 720 
  Number of stims on node 87: 710 
  Number of stims on node 72: 710 
  Number of stims on node 106: 710 
  Number of stims on node 68: 710 
  Number of stims on node 35: 720 
  Number of stims on node 105: 710 
  Number of stims on node 2: 720 
  Number of stims on node 32: 720 
  Number of stims on node 92: 710 
  Number of stims on node 70: 710 
  Number of stims on node 57: 710 
  Number of stims on node 28: 720 
  Number of stims on node 7: 720 
  Number of stims on node 34: 720 
  Number of stims on node 84: 710 
  Number of stims on node 20: 720 
  Number of stims on node 42: 720 
  Number of stims on node 78: 710 
  Number of stims on node 12: 720 
  Number of stims on node 27: 720 
  Number of stims on node 67: 710 
  Number of stims on node 26: 720 
  Number of stims on node 38: 720 
  Number of stims on node 91: 710 
  Number of stims on node 3: 720 
  Number of stims on node 100: 710 
  Number of stims on node 52: 710 
  Number of stims on node 86: 710 
  Number of stims on node 25: 720 
  Number of stims on node 82: 710 
  Number of stims on node 8: 720 
  Number of stims on node 102: 710 
  Number of stims on node 76: 710 
  Number of stims on node 66: 710 
  Number of stims on node 4: 720 
  Number of stims on node 75: 710 
  Number of stims on node 44: 720 
  Number of stims on node 13: 720 
  Number of stims on node 96: 710 
  Number of stims on node 51: 710 
  Number of stims on node 15: 720 
  Number of stims on node 10: 720 
  Number of stims on node 74: 710 
  Number of stims on node 16: 720 
  Number of stims on node 24: 720 
  Number of stims on node 23: 720 
  Number of stims on node 103: 710 
  Number of stims on node 0: 720 
  Number of stims on node 18: 720 
  Number of stims on node 65: 710 
  Number of stims on node 108: 710 
  Number of stims on node 9: 720 
  Number of stims on node 98: 710 
  Number of stims on node 31: 720 
  Number of stims on node 99: 710 
  Number of stims on node 30: 720 
  Number of stims on node 64: 710 
  Number of stims on node 77: 710 
  Number of stims on node 47: 720 
  Number of stims on node 80: 710 
  Number of stims on node 88: 710 
  Number of stims on node 17: 720 
  Number of stims on node 95: 710 
  Number of stims on node 60: 710 
  Number of stims on node 109: 710 
  Number of stims on node 58: 710 
  Number of stims on node 50: 710 
  Number of stims on node 46: 720 
  Number of stims on node 29: 720 
  Number of stims on node 48: 720 
  Number of stims on node 39: 720 
  Number of stims on node 49: 710 
  Number of stims on node 79: 710 
  Number of stims on node 85: 710 
  Number of stims on node 21: 720 
  Number of stims on node 5: 720 
  Number of stims on node 94: 710 
  Number of stims on node 81: 710 
  Number of stims on node 59: 710 
  Number of stims on node 61: 710 
  Number of stims on node 11: 720 
  Number of stims on node 107: 710 
  Number of stims on node 41: 720 
  Number of stims on node 83: 710 
  Number of stims on node 69: 710 
  Number of stims on node 104: 710 
  Number of stims on node 43: 720 
  Number of stims on node 19: 720 
  Number of stims on node 93: 710 
  Number of stims on node 40: 720 
  Number of stims on node 62: 710 
  Number of stims on node 55: 710 
  Number of stims on node 73: 710 
  Number of stims on node 101: 710 
  Number of stims on node 53: 710 
  Number of stims on node 54: 710 
  Number of stims on node 63: 710 
  Number of stims on node 90: 710 
  Number of stims on node 36: 720 
  Number of stims on node 71: 710 
  Number of stims on node 56: 710 
  Number of stims on node 37: 720 
  Number of stims on node 14: 720 
  Done; cell stims creation time = 3.72 s.
  Number of stims on node 33: 720 
Recording 9 traces of 1 types on node 78
Recording 6 traces of 1 types on node 67
Recording 4 traces of 1 types on node 89
Recording 4 traces of 1 types on node 37
Recording 6 traces of 1 types on node 22
Recording 6 traces of 1 types on node 6
Recording 8 traces of 1 types on node 96
Recording 9 traces of 1 types on node 45
Recording 5 traces of 1 types on node 32
Recording 5 traces of 1 types on node 63
Recording 5 traces of 1 types on node 12
Recording 9 traces of 1 types on node 3
Recording 6 traces of 1 types on node 106
Recording 6 traces of 1 types on node 30
Recording 7 traces of 1 types on node 97
Recording 9 traces of 1 types on node 74
Recording 3 traces of 1 types on node 25
Recording 8 traces of 1 types on node 87
Recording 8 traces of 1 types on node 84
Recording 8 traces of 1 types on node 75
Recording 6 traces of 1 types on node 10
Recording 7 traces of 1 types on node 98
Recording 5 traces of 1 types on node 91
Recording 7 traces of 1 types on node 65
Recording 6 traces of 1 types on node 57
Recording 7 traces of 1 types on node 60
Recording 6 traces of 1 types on node 38
Recording 7 traces of 1 types on node 72
Recording 5 traces of 1 types on node 100
Recording 5 traces of 1 types on node 64
Recording 3 traces of 1 types on node 27
Recording 7 traces of 1 types on node 47
Recording 8 traces of 1 types on node 44
Recording 5 traces of 1 types on node 66
Recording 2 traces of 1 types on node 26
Recording 3 traces of 1 types on node 24
Recording 7 traces of 1 types on node 52
Recording 1 traces of 1 types on node 35
Recording 5 traces of 1 types on node 103
Recording 3 traces of 1 types on node 34
Recording 7 traces of 1 types on node 59
Recording 4 traces of 1 types on node 23
Recording 8 traces of 1 types on node 5
Recording 5 traces of 1 types on node 20
Recording 5 traces of 1 types on node 102
Recording 6 traces of 1 types on node 88
Recording 5 traces of 1 types on node 11
Recording 6 traces of 1 types on node 13
Recording 9 traces of 1 types on node 4
Recording 7 traces of 1 types on node 39
Recording 8 traces of 1 types on node 41
Recording 4 traces of 1 types on node 54
Recording 7 traces of 1 types on node 46
Recording 6 traces of 1 types on node 21
Recording 6 traces of 1 types on node 92
Recording 6 traces of 1 types on node 16
Recording 8 traces of 1 types on node 2
Recording 9 traces of 1 types on node 42
Recording 6 traces of 1 types on node 82
Recording 8 traces of 1 types on node 58
Recording 6 traces of 1 types on node 8
Recording 7 traces of 1 types on node 43
Recording 6 traces of 1 types on node 94
Recording 5 traces of 1 types on node 17
Recording 3 traces of 1 types on node 109
Recording 7 traces of 1 types on node 7
Recording 8 traces of 1 types on node 73
Recording 10 traces of 1 types on node 76
Recording 8 traces of 1 types on node 80
Recording 7 traces of 1 types on node 62
Recording 8 traces of 1 types on node 86
Recording 7 traces of 1 types on node 104
Recording 6 traces of 1 types on node 71
Recording 6 traces of 1 types on node 81
Recording 7 traces of 1 types on node 40
Recording 6 traces of 1 types on node 14
Recording 5 traces of 1 types on node 99
Recording 7 traces of 1 types on node 79
Recording 5 traces of 1 types on node 108
Recording 9 traces of 1 types on node 85
Recording 7 traces of 1 types on node 18
Recording 5 traces of 1 types on node 56
Recording 1 traces of 1 types on node 36
Recording 2 traces of 1 types on node 28
Recording 7 traces of 1 types on node 83
Recording 7 traces of 1 types on node 51
Recording 5 traces of 1 types on node 55
Recording 5 traces of 1 types on node 69
Recording 10 traces of 1 types on node 77
Recording 6 traces of 1 types on node 33
Recording 7 traces of 1 types on node 48
Recording 6 traces of 1 types on node 70
Recording 6 traces of 1 types on node 95
Recording 6 traces of 1 types on node 107
Recording 5 traces of 1 types on node 101
Recording 6 traces of 1 types on node 105
Recording 6 traces of 1 types on node 90
Recording 4 traces of 1 types on node 29
Recording 6 traces of 1 types on node 15
Recording 6 traces of 1 types on node 68
Recording 6 traces of 1 types on node 31
Recording 5 traces of 1 types on node 53
Recording 7 traces of 1 types on node 93
Recording 4 traces of 1 types on node 0
Recording 7 traces of 1 types on node 1
Recording 5 traces of 1 types on node 19
Recording 7 traces of 1 types on node 50
Recording 6 traces of 1 types on node 9
Recording 8 traces of 1 types on node 49
Recording 8 traces of 1 types on node 61
0.0s

Running simulation for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 4478.69 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 2.95 s.

Analyzing...
[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m  Cells: 7859
  Connections: 0 (0.00 per cell)
  Spikes: 6691 (0.43 Hz)
  Simulated time: 2.0 s; 110 workers
  Run time: 4478.69 s
   L1_DAC : 0.000 Hz
[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.000 Hz
   L1_NGC-SA : 0.000 Hz
   L1_SLAC : 0.000 Hz
   L23_BP : 0.062 Hz
   L23_BTC : 0.000 Hz
   L23_ChC : 0.031 Hz
   L23_DBC : 0.000 Hz
   L23_LBC : 0.083 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.008 Hz
   L23_NGC : 0.000 Hz
   L23_PC : 0.008 Hz
   L23_SBC : 0.244 Hz
   L4_BP : 0.000 Hz
   L4_BTC : 0.062 Hz
   L4_ChC : 0.667 Hz
   L4_DBC : 0.000 Hz
   L4_LBC : 1.230 Hz
   L4_MC : 0.000 Hz
   L4_NBC : 1.839 Hz
   L4_NGC : 0.125 Hz
   L4_PC : 0.217 Hz
   L4_SBC : 1.750 Hz
   L4_SP : 0.231 Hz
   L4_SS : 0.412 Hz
   L5_BP : 2.250 Hz
   L5_BTC : 1.023 Hz
   L5_ChC : 4.100 Hz
   L5_DBC : 0.125 Hz
   L5_LBC : 2.328 Hz
   L5_MC : 0.023 Hz
   L5_NBC : 1.393 Hz
   L5_NGC : 2.875 Hz
   L5_SBC : 2.750 Hz
   L5_STPC : 0.386 Hz
   L5_TTPC1 : 0.284 Hz
   L5_TTPC2 : 0.250 Hz
   L5_UTPC : 0.888 Hz
   L6_BPC : 0.456 Hz
   L6_BP : 1.500 Hz
   L6_BTC : 2.273 Hz
   L6_ChC : 8.667 Hz
   L6_DBC : 0.125 Hz
   L6_IPC : 0.801 Hz
   L6_LBC : 3.100 Hz
   L6_MC : 0.056 Hz
   L6_NBC : 3.762 Hz
   L6_NGC : 1.600 Hz
   L6_SBC : 5.071 Hz
   L6_TPC_L1 : 0.383 Hz
   L6_TPC_L4 : 0.596 Hz
   L6_UTPC : 0.721 Hz
Saving output as ../data/v0_batch4/v0_batch4_0_0.json  ... 
Finished saving!
  Done; saving time = 24.25 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 109.97 s

Total time = 6484.74 s

End time:  2021-04-11 16:46:46.658787
[0m