numprocs=40

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch4/v1_batch4_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py

Start time:  2021-06-21 19:18:38.770940
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py
Importing netParams from ../data/v1_batch4/v1_batch4_netParams.py

Creating network of 61 cell populations on 40 hosts...
  Number of cells on node 10: 110 
  Number of cells on node 14: 110 
  Number of cells on node 38: 109 
  Number of cells on node 28: 109 
  Number of cells on node 3: 110 
  Number of cells on node 39: 109 
  Number of cells on node 0: 110 
  Done; cell creation time = 0.68 s.
Making connections...
  Number of cells on node 13: 110 
  Number of cells on node 16: 110 
  Number of cells on node 25: 109 
  Number of cells on node 6: 110 
  Number of cells on node 29: 109 
  Number of cells on node 33: 109 
  Number of cells on node 21: 110 
  Number of cells on node 17: 110 
  Number of cells on node 1: 110 
  Number of cells on node 24: 109 
  Number of cells on node 2: 110 
  Number of cells on node 9: 110 
  Number of cells on node 11: 110 
  Number of cells on node 15: 110 
  Number of cells on node 31: 109 
  Number of cells on node 4: 110 
  Number of cells on node 23: 110 
  Number of cells on node 19: 110 
  Number of cells on node 20: 110 
  Number of cells on node 34: 109 
  Number of cells on node 27: 109 
  Number of cells on node 26: 109 
  Number of cells on node 30: 109 
  Number of cells on node 12: 110 
  Number of cells on node 8: 110 
  Number of cells on node 5: 110 
  Number of cells on node 18: 110 
  Number of cells on node 36: 109 
  Number of cells on node 37: 109 
  Number of cells on node 7: 110 
  Number of cells on node 22: 110 
  Number of cells on node 32: 109 
  Number of cells on node 35: 109 
  Number of connections on node 0: 1784 
  Number of synaptic contacts on node 0: 25640 
  Number of connections on node 4: 1926 
  Number of synaptic contacts on node 4: 27640 
  Number of connections on node 2: 1907 
  Number of synaptic contacts on node 2: 27180 
  Number of connections on node 38: 1952 
  Number of synaptic contacts on node 38: 27930 
  Number of connections on node 8: 1861 
  Number of synaptic contacts on node 8: 26420 
  Number of connections on node 18: 1842 
  Number of synaptic contacts on node 18: 26680 
  Number of connections on node 10: 1783 
  Number of synaptic contacts on node 10: 25790 
  Number of connections on node 30: 1919 
  Number of synaptic contacts on node 30: 27540 
  Number of connections on node 32: 1909 
  Number of synaptic contacts on node 32: 27300 
  Number of connections on node 26: 1881 
  Number of synaptic contacts on node 26: 26910 
  Number of connections on node 28: 1765 
  Number of synaptic contacts on node 28: 25640 
  Number of connections on node 14: 1844 
  Number of synaptic contacts on node 14: 26910 
  Number of connections on node 36: 1999 
  Number of synaptic contacts on node 36: 28570 
  Number of connections on node 6: 1870 
  Number of synaptic contacts on node 6: 27470 
  Number of connections on node 20: 1949 
  Number of synaptic contacts on node 20: 28390 
  Number of connections on node 22: 1849 
  Number of synaptic contacts on node 22: 26690 
  Number of connections on node 16: 1704 
  Number of synaptic contacts on node 16: 25500 
  Number of connections on node 12: 1913 
  Number of synaptic contacts on node 12: 27700 
  Number of connections on node 24: 1874 
  Number of synaptic contacts on node 24: 26690 
  Number of connections on node 34: 1732 
  Number of synaptic contacts on node 34: 25970 
  Number of connections on node 1: 1779 
  Number of synaptic contacts on node 1: 25600 
  Number of connections on node 33: 1987 
  Number of synaptic contacts on node 33: 28380 
  Number of connections on node 7: 1911 
  Number of synaptic contacts on node 7: 27510 
  Number of connections on node 25: 1892 
  Number of synaptic contacts on node 25: 27400 
  Number of connections on node 9: 1899 
  Number of synaptic contacts on node 9: 27380 
  Number of connections on node 17: 1861 
  Number of synaptic contacts on node 17: 26570 
  Number of connections on node 35: 1996 
  Number of synaptic contacts on node 35: 28450 
  Number of connections on node 15: 1884 
  Number of synaptic contacts on node 15: 27950 
  Number of connections on node 23: 1884 
  Number of synaptic contacts on node 23: 27040 
  Number of connections on node 5: 1814 
  Number of synaptic contacts on node 5: 26270 
  Number of connections on node 37: 1857 
  Number of synaptic contacts on node 37: 27310 
  Number of connections on node 21: 1923 
  Number of synaptic contacts on node 21: 27630 
  Number of connections on node 19: 1893 
  Number of synaptic contacts on node 19: 27010 
  Number of connections on node 29: 1993 
  Number of synaptic contacts on node 29: 28110 
  Number of connections on node 39: 2001 
  Number of synaptic contacts on node 39: 29010 
  Number of connections on node 27: 1925 
  Number of synaptic contacts on node 27: 27410 
  Number of connections on node 31: 1917 
  Number of synaptic contacts on node 31: 28080 
  Number of connections on node 11: 1898 
  Number of synaptic contacts on node 11: 27090 
  Number of connections on node 3: 1811 
  Number of synaptic contacts on node 3: 26340 
  Done; cell connection time = 43.33 s.
  Number of connections on node 13: 1793 
  Number of synaptic contacts on node 13: 26230 
Adding stims...
  Number of stims on node 0: 54 
  Number of stims on node 17: 55 
  Number of stims on node 13: 55 
  Number of stims on node 22: 55 
  Number of stims on node 36: 54 
  Number of stims on node 1: 54 
  Number of stims on node 37: 54 
  Number of stims on node 9: 55 
  Number of stims on node 34: 54 
  Number of stims on node 12: 55 
  Number of stims on node 4: 55 
  Number of stims on node 25: 54 
  Number of stims on node 27: 54 
  Number of stims on node 21: 55 
  Number of stims on node 6: 55 
  Number of stims on node 24: 54 
  Number of stims on node 39: 54 
  Number of stims on node 10: 55 
  Number of stims on node 16: 55 
  Number of stims on node 38: 54 
  Number of stims on node 23: 55 
  Number of stims on node 8: 55 
  Number of stims on node 5: 55 
  Number of stims on node 33: 54 
  Number of stims on node 20: 55 
  Number of stims on node 18: 55 
  Number of stims on node 28: 54 
  Number of stims on node 2: 54 
  Number of stims on node 26: 54 
  Number of stims on node 11: 55 
  Number of stims on node 3: 54 
  Number of stims on node 32: 54 
  Number of stims on node 30: 54 
  Number of stims on node 29: 54 
  Number of stims on node 31: 54 
  Number of stims on node 35: 54 
  Number of stims on node 14: 55 
  Number of stims on node 7: 55 
  Number of stims on node 19: 55 
  Done; cell stims creation time = 0.15 s.
  Number of stims on node 15: 55 
Recording 1 traces of 1 types on node 38
Recording 0 traces of 0 types on node 30
Recording 2 traces of 1 types on node 2
Recording 1 traces of 1 types on node 17
Recording 1 traces of 1 types on node 12
Recording 1 traces of 1 types on node 11
Recording 1 traces of 1 types on node 10
Recording 1 traces of 1 types on node 35
Recording 2 traces of 1 types on node 8
Recording 2 traces of 1 types on node 28
Recording 0 traces of 0 types on node 14
Recording 1 traces of 1 types on node 29
Recording 3 traces of 1 types on node 25
Recording 3 traces of 1 types on node 21
Recording 0 traces of 0 types on node 16
Recording 0 traces of 0 types on node 33
Recording 1 traces of 1 types on node 18
Recording 3 traces of 1 types on node 4
Recording 0 traces of 0 types on node 31
Recording 2 traces of 1 types on node 0
Recording 3 traces of 1 types on node 22
Recording 2 traces of 1 types on node 7
Recording 1 traces of 1 types on node 36
Recording 0 traces of 0 types on node 34
Recording 3 traces of 1 types on node 20
Recording 3 traces of 1 types on node 26
Recording 1 traces of 1 types on node 37
Recording 2 traces of 1 types on node 6
Recording 1 traces of 1 types on node 13
Recording 2 traces of 1 types on node 1
Recording 2 traces of 1 types on node 3
Recording 1 traces of 1 types on node 9
Recording 2 traces of 1 types on node 27
Recording 0 traces of 0 types on node 32
Recording 0 traces of 0 types on node 15
Recording 3 traces of 1 types on node 24
Recording 2 traces of 1 types on node 39
Recording 3 traces of 1 types on node 23
Recording 2 traces of 1 types on node 19
Recording 2 traces of 1 types on node 5
0.0s

Running simulation for 20000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
5.0s
5.1s
5.2s
5.3s
5.4s
5.5s
5.6s
5.7s
5.8s
5.9s
6.0s
6.1s
6.2s
6.3s
6.4s
6.5s
6.6s
6.7s
6.8s
6.9s
7.0s
7.1s
7.2s
7.3s
7.4s
7.5s
7.6s
7.7s
7.8s
7.9s
8.0s
8.1s
8.2s
8.3s
8.4s
8.5s
8.6s
8.7s
8.8s
8.9s
9.0s
9.1s
9.2s
9.3s
9.4s
9.5s
9.6s
9.7s
9.8s
9.9s
10.0s
10.1s
10.2s
10.3s
10.4s
10.5s
10.6s
10.7s
10.8s
10.9s
11.0s
11.1s
11.2s
11.3s
11.4s
11.5s
11.6s
11.7s
11.8s
11.9s
12.0s
12.1s
12.2s
12.3s
12.4s
12.5s
12.6s
12.7s
12.8s
12.9s
13.0s
13.1s
13.2s
13.3s
13.4s
13.5s
13.6s
13.7s
13.8s
13.9s
14.0s
14.1s
14.2s
14.3s
14.4s
14.5s
14.6s
14.7s
14.8s
14.9s
15.0s
15.1s
15.2s
15.3s
15.4s
15.5s
15.6s
15.7s
15.8s
15.9s
16.0s
16.1s
16.2s
16.3s
16.4s
16.5s
16.6s
16.7s
16.8s
16.9s
17.0s
17.1s
17.2s
17.3s
17.4s
17.5s
17.6s
17.7s
17.8s
17.9s
18.0s
18.1s
18.2s
18.3s
18.4s
18.5s
18.6s
18.7s
18.8s
18.9s
19.0s
19.1s
19.2s
19.3s
19.4s
19.5s
19.6s
19.7s
19.8s
19.9s
  Done; run time = 3759.62 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.66 s.

Analyzing...
  Cells: 4384
  Connections: 0 (0.00 per cell)
  Spikes: 608321 (6.94 Hz)
  Simulated time: 20.0 s; 40 workers
  Run time: 3759.62 s
   L1_DAC : 0.000 Hz
   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.000 Hz
   L1_NGC-SA : 0.000 Hz
   L1_SLAC : 0.000 Hz
   L23_BP : 0.000 Hz
   L23_BTC : 0.000 Hz
   L23_ChC : 0.000 Hz
   L23_DBC : 0.000 Hz
   L23_LBC : 0.000 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.000 Hz
   L23_NGC : 0.000 Hz
   L23_PC : 0.000 Hz
   L23_SBC : 0.000 Hz
   L4_BP : 0.000 Hz
   L4_BTC : 0.000 Hz
   L4_ChC : 0.000 Hz
   L4_DBC : 0.000 Hz
   L4_LBC : 0.000 Hz
   L4_MC : 0.000 Hz
   L4_NBC : 0.000 Hz
   L4_NGC : 0.000 Hz
   L4_PC : 0.000 Hz
   L4_SBC : 0.000 Hz
   L4_SP : 0.000 Hz
   L4_SS : 0.000 Hz
   L5_BP : 0.000 Hz
   L5_BTC : 0.000 Hz
   L5_ChC : 0.000 Hz
   L5_DBC : 0.000 Hz
   L5_LBC : 0.000 Hz
   L5_MC : 0.000 Hz
   L5_NBC : 0.000 Hz
   L5_NGC : 0.000 Hz
   L5_SBC : 0.000 Hz
   L5_STPC : 0.000 Hz
   L5_TTPC1 : 0.000 Hz
   L5_TTPC2 : 0.000 Hz
   L5_UTPC : 0.000 Hz
   L6_BPC : 0.000 Hz
   L6_BP : 0.000 Hz
   L6_BTC : 0.000 Hz
   L6_ChC : 0.000 Hz
   L6_DBC : 0.000 Hz
   L6_IPC : 0.000 Hz
   L6_LBC : 0.000 Hz
   L6_MC : 0.000 Hz
   L6_NBC : 0.000 Hz
   L6_NGC : 0.000 Hz
   L6_SBC : 0.000 Hz
   L6_TPC_L1 : 0.000 Hz
   L6_TPC_L4 : 0.000 Hz
   L6_UTPC : 0.000 Hz
   ss_RTN_o : 13.718 Hz
   ss_RTN_m : 15.735 Hz
   ss_RTN_i : 15.544 Hz
   VPL_sTC : 3.018 Hz
   VPM_sTC : 2.656 Hz
   POm_sTC_s1 : 4.476 Hz
Saving output as ../data/v1_batch4/v1_batch4_0.json  ... 
Finished saving!
  Done; saving time = 0.03 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 474.45 s

Total time = 4310.11 s

End time:  2021-06-21 20:30:28.882394
