numprocs=40

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch7/v1_batch7_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py

Start time:  2021-06-24 17:31:15.222487
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py
Importing netParams from ../data/v1_batch7/v1_batch7_netParams.py

Creating network of 61 cell populations on 40 hosts...
  Number of cells on node 33: 289 
  Number of cells on node 36: 289 
  Number of cells on node 25: 289 
  Number of cells on node 18: 289 
  Number of cells on node 31: 289 
  Number of cells on node 30: 289 
  Number of cells on node 35: 289 
  Number of cells on node 11: 289 
  Number of cells on node 27: 289 
  Number of cells on node 28: 289 
  Number of cells on node 38: 289 
  Number of cells on node 26: 289 
  Number of cells on node 29: 289 
  Number of cells on node 32: 289 
  Number of cells on node 37: 289 
  Number of cells on node 1: 290 
  Number of cells on node 9: 289 
  Number of cells on node 21: 289 
  Number of cells on node 34: 289 
  Number of cells on node 24: 289 
  Number of cells on node 4: 290 
  Number of cells on node 10: 289 
  Number of cells on node 19: 289 
  Number of cells on node 23: 289 
  Number of cells on node 17: 289 
  Number of cells on node 7: 290 
  Number of cells on node 6: 290 
  Number of cells on node 14: 289 
  Number of cells on node 5: 290 
  Number of cells on node 8: 289 
  Number of cells on node 22: 289 
  Number of cells on node 16: 289 
  Number of cells on node 12: 289 
  Number of cells on node 20: 289 
  Number of cells on node 13: 289 
  Number of cells on node 3: 290 
  Number of cells on node 15: 289 
  Number of cells on node 39: 289 
  Number of cells on node 2: 290 
  Number of cells on node 0: 290 
  Done; cell creation time = 1.12 s.
Making connections...
  Number of connections on node 33: 2079 
  Number of synaptic contacts on node 33: 6088 
  Number of connections on node 20: 2010 
  Number of synaptic contacts on node 20: 6074 
  Number of connections on node 0: 1912 
  Number of synaptic contacts on node 0: 5645 
  Number of connections on node 31: 2010 
  Number of synaptic contacts on node 31: 6040 
  Number of connections on node 3: 2022 
  Number of synaptic contacts on node 3: 6250 
  Number of connections on node 17: 1949 
  Number of synaptic contacts on node 17: 5869 
  Number of connections on node 15: 2116 
  Number of synaptic contacts on node 15: 5896 
  Number of connections on node 1: 1933 
  Number of synaptic contacts on node 1: 6326 
  Number of connections on node 22: 2028 
  Number of synaptic contacts on node 22: 5912 
  Number of connections on node 8: 2087 
  Number of synaptic contacts on node 8: 5834 
  Number of connections on node 27: 2059 
  Number of synaptic contacts on node 27: 5742 
  Number of connections on node 38: 2054 
  Number of synaptic contacts on node 38: 6191 
  Number of connections on node 13: 1999 
  Number of synaptic contacts on node 13: 5687 
  Number of connections on node 36: 1988 
  Number of synaptic contacts on node 36: 6183 
  Number of connections on node 25: 2066 
  Number of synaptic contacts on node 25: 5875 
  Number of connections on node 2: 2002 
  Number of synaptic contacts on node 2: 6098 
  Number of connections on node 19: 1954 
  Number of synaptic contacts on node 19: 5897 
  Number of connections on node 9: 1983 
  Number of synaptic contacts on node 9: 5658 
  Number of connections on node 5: 1947 
  Number of synaptic contacts on node 5: 6216 
  Number of connections on node 28: 2038 
  Number of synaptic contacts on node 28: 6169 
  Number of connections on node 12: 2048 
  Number of synaptic contacts on node 12: 5649 
  Number of connections on node 24: 1984 
  Number of synaptic contacts on node 24: 6038 
  Number of connections on node 16: 2114 
  Number of synaptic contacts on node 16: 6216 
  Number of connections on node 35: 2062 
  Number of synaptic contacts on node 35: 5603 
  Number of connections on node 11: 2141 
  Number of synaptic contacts on node 11: 6258 
  Number of connections on node 18: 2018 
  Number of synaptic contacts on node 18: 5753 
  Number of connections on node 7: 2103 
  Number of synaptic contacts on node 7: 6289 
  Number of connections on node 29: 2064 
  Number of synaptic contacts on node 29: 6413 
  Number of connections on node 4: 2114 
  Number of synaptic contacts on node 4: 6013 
  Number of connections on node 30: 2032 
  Number of synaptic contacts on node 30: 6231 
  Number of connections on node 26: 2100 
  Number of synaptic contacts on node 26: 5898 
  Number of connections on node 37: 1936 
  Number of synaptic contacts on node 37: 5712 
  Number of connections on node 14: 2186 
  Number of synaptic contacts on node 14: 6222 
  Number of connections on node 34: 2041 
  Number of synaptic contacts on node 34: 6029 
  Number of connections on node 32: 1968 
  Number of synaptic contacts on node 32: 6088 
  Number of connections on node 23: 2094 
  Number of synaptic contacts on node 23: 6205 
  Number of connections on node 21: 2036 
  Number of synaptic contacts on node 21: 6296 
  Number of connections on node 39: 1949 
  Number of synaptic contacts on node 39: 6079 
  Number of connections on node 10: 2114 
  Number of synaptic contacts on node 10: 5959 
  Number of connections on node 6: 2020 
  Number of synaptic contacts on node 6: 5935 
  Done; cell connection time = 58.09 s.
Adding stims...
  Number of stims on node 39: 2015 
  Number of stims on node 36: 2015 
  Number of stims on node 29: 2015 
  Number of stims on node 35: 2015 
  Number of stims on node 13: 2024 
  Number of stims on node 4: 2025 
  Number of stims on node 25: 2014 
  Number of stims on node 23: 2014 
  Number of stims on node 20: 2014 
  Number of stims on node 11: 2024 
  Number of stims on node 33: 2015 
  Number of stims on node 30: 2015 
  Number of stims on node 12: 2024 
  Number of stims on node 28: 2015 
  Number of stims on node 27: 2014 
  Number of stims on node 18: 2024 
  Number of stims on node 16: 2024 
  Number of stims on node 2: 2025 
  Number of stims on node 14: 2024 
  Number of stims on node 38: 2015 
  Number of stims on node 31: 2015 
  Number of stims on node 10: 2024 
  Number of stims on node 9: 2024 
  Number of stims on node 5: 2025 
  Number of stims on node 6: 2025 
  Number of stims on node 26: 2014 
  Number of stims on node 19: 2014 
  Number of stims on node 15: 2024 
  Number of stims on node 0: 2025 
  Number of stims on node 3: 2025 
  Number of stims on node 32: 2015 
  Number of stims on node 34: 2015 
  Number of stims on node 7: 2025 
  Number of stims on node 1: 2025 
  Number of stims on node 37: 2015 
  Number of stims on node 24: 2014 
  Number of stims on node 21: 2014 
  Number of stims on node 22: 2014 
  Number of stims on node 17: 2024 
  Number of stims on node 8: 2024 
  Done; cell stims creation time = 2.29 s.
Recording 1 traces of 1 types on node 35
Recording 3 traces of 1 types on node 4
Recording 2 traces of 1 types on node 30
Recording 2 traces of 1 types on node 31
Recording 0 traces of 0 types on node 38
Recording 2 traces of 1 types on node 23
Recording 0 traces of 0 types on node 39
Recording 1 traces of 1 types on node 20
Recording 1 traces of 1 types on node 13
Recording 0 traces of 0 types on node 18
Recording 2 traces of 1 types on node 29
Recording 1 traces of 1 types on node 2
Recording 0 traces of 0 types on node 14
Recording 0 traces of 0 types on node 17
Recording 3 traces of 1 types on node 28
Recording 0 traces of 0 types on node 16
Recording 3 traces of 1 types on node 6
Recording 1 traces of 1 types on node 36
Recording 0 traces of 0 types on node 15
Recording 3 traces of 1 types on node 9
Recording 2 traces of 1 types on node 11
Recording 2 traces of 1 types on node 3
Recording 3 traces of 1 types on node 5
Recording 1 traces of 1 types on node 33
Recording 1 traces of 1 types on node 19
Recording 3 traces of 1 types on node 7
Recording 2 traces of 1 types on node 25
Recording 3 traces of 1 types on node 10
Recording 1 traces of 1 types on node 37
Recording 1 traces of 1 types on node 21
Recording 1 traces of 1 types on node 22
Recording 2 traces of 1 types on node 27
Recording 1 traces of 1 types on node 1
Recording 0 traces of 0 types on node 0
Recording 1 traces of 1 types on node 34
Recording 3 traces of 1 types on node 8
Recording 2 traces of 1 types on node 12
Recording 2 traces of 1 types on node 32
Recording 2 traces of 1 types on node 26
Recording 2 traces of 1 types on node 24
0.0s

Running simulation for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 85.84 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.89 s.

Analyzing...
  Cells: 11568
  Connections: 0 (0.00 per cell)
  Spikes: 231952 (10.03 Hz)
  Simulated time: 2.0 s; 40 workers
  Run time: 85.84 s
   L1_DAC : 0.000 Hz
   L1_DLAC : 0.000 Hz
   L1_HAC : 0.000 Hz
   L1_NGC-DA : 0.000 Hz
   L1_NGC-SA : 0.000 Hz
   L1_SLAC : 0.000 Hz
   L23_BP : 0.500 Hz
   L23_BTC : 0.000 Hz
   L23_ChC : 0.031 Hz
   L23_DBC : 0.058 Hz
   L23_LBC : 0.018 Hz
   L23_MC : 0.000 Hz
   L23_NBC : 0.008 Hz
   L23_NGC : 0.000 Hz
   L23_PC : 0.178 Hz
   L23_SBC : 0.073 Hz
   L4_BP : 0.583 Hz
   L4_BTC : 0.438 Hz
   L4_ChC : 6.667 Hz
   L4_DBC : 0.273 Hz
   L4_LBC : 2.000 Hz
   L4_MC : 0.015 Hz
   L4_NBC : 2.250 Hz
   L4_NGC : 1.375 Hz
   L4_PC : 2.304 Hz
   L4_SBC : 5.167 Hz
   L4_SP : 3.369 Hz
   L4_SS : 4.500 Hz
   L5_BP : 10.688 Hz
   L5_BTC : 1.705 Hz
   L5_ChC : 27.000 Hz
   L5_DBC : 1.167 Hz
   L5_LBC : 10.431 Hz
   L5_MC : 0.065 Hz
   L5_NBC : 19.054 Hz
   L5_NGC : 8.250 Hz
   L5_SBC : 18.750 Hz
   L5_STPC : 5.819 Hz
   L5_TTPC1 : 24.279 Hz
   L5_TTPC2 : 20.484 Hz
   L5_UTPC : 30.069 Hz
   L6_BPC : 15.190 Hz
   L6_BP : 10.893 Hz
   L6_BTC : 12.545 Hz
   L6_ChC : 45.000 Hz
   L6_DBC : 6.688 Hz
   L6_IPC : 15.336 Hz
   L6_LBC : 18.325 Hz
   L6_MC : 0.062 Hz
   L6_NBC : 26.274 Hz
   L6_NGC : 8.700 Hz
   L6_SBC : 31.750 Hz
   L6_TPC_L1 : 14.982 Hz
   L6_TPC_L4 : 7.101 Hz
   L6_UTPC : 15.480 Hz
   ss_RTN_o : 15.334 Hz
   ss_RTN_m : 16.813 Hz
   ss_RTN_i : 16.003 Hz
   VPL_sTC : 6.933 Hz
   VPM_sTC : 5.265 Hz
   POm_sTC_s1 : 9.260 Hz
Saving output as ../data/v1_batch7/v1_batch7_0.json  ... 
Finished saving!
  Done; saving time = 0.02 s.
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 205.60 s

Total time = 370.70 s

End time:  2021-06-24 17:37:25.920554
