numprocs=80

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v1_batch6/v1_batch6_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py

Start time:  2021-06-29 16:30:39.358229
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py
Importing netParams from ../data/v1_batch6/v1_batch6_netParams.py

Creating network of 61 cell populations on 80 hosts...
  Number of cells on node 19: 145 
  Number of cells on node 47: 145 
  Number of cells on node 74: 144 
  Number of cells on node 36: 145 
  Number of cells on node 31: 145 
  Number of cells on node 28: 145 
  Number of cells on node 44: 145 
  Number of cells on node 9: 145 
  Number of cells on node 71: 144 
  Number of cells on node 53: 144 
  Number of cells on node 32: 145 
  Number of cells on node 52: 144 
  Number of cells on node 3: 145 
  Number of cells on node 35: 145 
  Number of cells on node 48: 144 
  Number of cells on node 79: 144 
  Number of cells on node 5: 145 
  Number of cells on node 10: 145 
  Number of cells on node 51: 144 
  Number of cells on node 54: 144 
  Number of cells on node 72: 144 
  Number of cells on node 59: 144 
  Number of cells on node 73: 144 
  Number of cells on node 22: 145 
  Number of cells on node 57: 144 
  Number of cells on node 18: 145 
  Number of cells on node 67: 144 
  Number of cells on node 7: 145 
  Number of cells on node 58: 144 
  Number of cells on node 27: 145 
  Number of cells on node 24: 145 
  Number of cells on node 38: 145 
  Number of cells on node 26: 145 
  Number of cells on node 37: 145 
  Number of cells on node 65: 144 
  Number of cells on node 4: 145 
  Number of cells on node 13: 145 
  Number of cells on node 61: 144 
  Number of cells on node 62: 144 
  Number of cells on node 23: 145 
  Number of cells on node 6: 145 
  Number of cells on node 33: 145 
  Number of cells on node 78: 144 
  Number of cells on node 76: 144 
  Number of cells on node 46: 145 
  Number of cells on node 55: 144 
  Number of cells on node 0: 145 
  Done; cell creation time = 13.87 s.
Making connections...
  Number of cells on node 56: 144 
  Number of cells on node 64: 144 
  Number of cells on node 11: 145 
  Number of cells on node 30: 145 
  Number of cells on node 14: 145 
  Number of cells on node 40: 145 
  Number of cells on node 25: 145 
  Number of cells on node 20: 145 
  Number of cells on node 70: 144 
  Number of cells on node 43: 145 
  Number of cells on node 34: 145 
  Number of cells on node 41: 145 
  Number of cells on node 17: 145 
  Number of cells on node 2: 145 
  Number of cells on node 29: 145 
  Number of cells on node 50: 144 
  Number of cells on node 68: 144 
  Number of cells on node 77: 144 
  Number of cells on node 39: 145 
  Number of cells on node 69: 144 
  Number of cells on node 42: 145 
  Number of cells on node 16: 145 
  Number of cells on node 12: 145 
  Number of cells on node 15: 145 
  Number of cells on node 8: 145 
  Number of cells on node 63: 144 
  Number of cells on node 21: 145 
  Number of cells on node 60: 144 
  Number of cells on node 75: 144 
  Number of cells on node 49: 144 
  Number of cells on node 45: 145 
  Number of cells on node 1: 145 
  Number of cells on node 66: 144 
  Number of connections on node 71: 27956 
  Number of synaptic contacts on node 71: 186401 
  Number of connections on node 77: 26996 
  Number of synaptic contacts on node 77: 182638 
  Number of connections on node 29: 28763 
  Number of synaptic contacts on node 29: 195306 
  Number of connections on node 48: 27534 
  Number of synaptic contacts on node 48: 185815 
  Number of connections on node 38: 27540 
  Number of synaptic contacts on node 38: 184660 
  Number of connections on node 60: 27442 
  Number of synaptic contacts on node 60: 189711 
  Number of connections on node 10: 27314 
  Number of synaptic contacts on node 10: 186971 
  Number of connections on node 67: 27737 
  Number of synaptic contacts on node 67: 185717 
  Number of connections on node 4: 27785 
  Number of synaptic contacts on node 4: 186755 
  Number of connections on node 8: 27425 
  Number of synaptic contacts on node 8: 188871 
  Number of connections on node 56: 27532 
  Number of synaptic contacts on node 56: 185097 
  Number of connections on node 70: 27702 
  Number of synaptic contacts on node 70: 189062 
  Number of connections on node 37: 27764 
  Number of synaptic contacts on node 37: 189981 
  Number of connections on node 73: 27338 
  Number of synaptic contacts on node 73: 188293 
  Number of connections on node 34: 26560 
  Number of synaptic contacts on node 34: 181795 
  Number of connections on node 14: 27778 
  Number of synaptic contacts on node 14: 191191 
  Number of connections on node 58: 27141 
  Number of synaptic contacts on node 58: 185208 
  Number of connections on node 52: 27436 
  Number of synaptic contacts on node 52: 182850 
  Number of connections on node 16: 28052 
  Number of synaptic contacts on node 16: 193089 
  Number of connections on node 0: 27741 
  Number of synaptic contacts on node 0: 189657 
  Number of connections on node 66: 26895 
  Number of synaptic contacts on node 66: 179798 
  Number of connections on node 59: 27433 
  Number of synaptic contacts on node 59: 188409 
  Number of connections on node 53: 27509 
  Number of synaptic contacts on node 53: 191466 
  Number of connections on node 11: 27023 
  Number of synaptic contacts on node 11: 182351 
  Number of connections on node 5: 26721 
  Number of synaptic contacts on node 5: 181611 
  Number of connections on node 42: 28601 
  Number of synaptic contacts on node 42: 189290 
  Number of connections on node 7: 27700 
  Number of synaptic contacts on node 7: 190709 
  Number of connections on node 1: 27140 
  Number of synaptic contacts on node 1: 187371 
  Number of connections on node 44: 28345 
  Number of synaptic contacts on node 44: 189133 
  Number of connections on node 17: 28189 
  Number of synaptic contacts on node 17: 192173 
  Number of connections on node 74: 26931 
  Number of synaptic contacts on node 74: 181353 
  Number of connections on node 21: 28334 
  Number of synaptic contacts on node 21: 188741 
  Number of connections on node 61: 27654 
  Number of synaptic contacts on node 61: 192880 
  Number of connections on node 31: 28699 
  Number of synaptic contacts on node 31: 190930 
  Number of connections on node 9: 27774 
  Number of synaptic contacts on node 9: 189598 
  Number of connections on node 41: 26914 
  Number of synaptic contacts on node 41: 182226 
  Number of connections on node 47: 28673 
  Number of synaptic contacts on node 47: 192614 
  Number of connections on node 78: 28073 
  Number of synaptic contacts on node 78: 193369 
  Number of connections on node 46: 28110 
  Number of synaptic contacts on node 46: 188985 
  Number of connections on node 25: 27862 
  Number of synaptic contacts on node 25: 187395 
  Number of connections on node 65: 28004 
  Number of synaptic contacts on node 65: 188234 
  Number of connections on node 63: 27966 
  Number of synaptic contacts on node 63: 186825 
  Number of connections on node 45: 27994 
  Number of synaptic contacts on node 45: 188633 
  Number of connections on node 79: 26774 
  Number of synaptic contacts on node 79: 187050 
  Number of connections on node 13: 27624 
  Number of synaptic contacts on node 13: 188202 
  Number of connections on node 50: 28021 
  Number of synaptic contacts on node 50: 189085 
  Number of connections on node 43: 28272 
  Number of synaptic contacts on node 43: 189469 
  Number of connections on node 28: 28011 
  Number of synaptic contacts on node 28: 190929 
  Number of connections on node 64: 27746 
  Number of synaptic contacts on node 64: 187657 
  Number of connections on node 24: 27288 
  Number of synaptic contacts on node 24: 187987 
  Number of connections on node 18: 26959 
  Number of synaptic contacts on node 18: 190469 
  Number of connections on node 75: 26968 
  Number of synaptic contacts on node 75: 183812 
  Number of connections on node 39: 27250 
  Number of synaptic contacts on node 39: 187978 
  Number of connections on node 26: 27686 
  Number of synaptic contacts on node 26: 188929 
  Number of connections on node 20: 28727 
  Number of synaptic contacts on node 20: 194410 
  Number of connections on node 69: 27359 
  Number of synaptic contacts on node 69: 183450 
  Number of connections on node 76: 27341 
  Number of synaptic contacts on node 76: 180673 
  Number of connections on node 19: 26929 
  Number of synaptic contacts on node 19: 182734 
  Number of connections on node 32: 28305 
  Number of synaptic contacts on node 32: 186962 
  Number of connections on node 6: 27618 
  Number of synaptic contacts on node 6: 186288 
  Number of connections on node 23: 28104 
  Number of synaptic contacts on node 23: 189298 
  Number of connections on node 62: 27808 
  Number of synaptic contacts on node 62: 188464 
  Number of connections on node 40: 27517 
  Number of synaptic contacts on node 40: 185347 
  Number of connections on node 12: 26780 
  Number of synaptic contacts on node 12: 188070 
  Number of connections on node 22: 27402 
  Number of synaptic contacts on node 22: 189210 
  Number of connections on node 57: 27350 
  Number of synaptic contacts on node 57: 189623 
  Number of connections on node 33: 27430 
  Number of synaptic contacts on node 33: 184935 
  Number of connections on node 68: 28114 
  Number of synaptic contacts on node 68: 189302 
  Number of connections on node 36: 27102 
  Number of synaptic contacts on node 36: 183235 
  Number of connections on node 27: 28219 
  Number of synaptic contacts on node 27: 185262 
  Number of connections on node 2: 26476 
  Number of synaptic contacts on node 2: 179569 
  Number of connections on node 55: 27409 
  Number of synaptic contacts on node 55: 178548 
  Number of connections on node 72: 26137 
  Number of synaptic contacts on node 72: 184040 
  Number of connections on node 51: 29184 
  Number of synaptic contacts on node 51: 193228 
  Number of connections on node 15: 27807 
  Number of synaptic contacts on node 15: 187825 
  Number of connections on node 49: 27097 
  Number of synaptic contacts on node 49: 191343 
  Number of connections on node 35: 27481 
  Number of synaptic contacts on node 35: 184543 
  Number of connections on node 30: 27193 
  Number of synaptic contacts on node 30: 184665 
  Number of connections on node 54: 27982 
  Number of synaptic contacts on node 54: 186466 
  Number of connections on node 3: 27305 
  Number of synaptic contacts on node 3: 183322 
  Done; cell connection time = 1455.99 s.

Gathering data...
  Done; gather time = 242.61 s.

Analyzing...
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f2f3df21f88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f151da4df88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7faa7542cdc8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fdb1720fe48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f1054ba6f48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fe7f1bf9448>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f363436cdc8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f4e2fe66e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fae2c93ee08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f99554a5f88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fb248a71e48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f3f7450a548>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f804029be08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f15c1ee6e48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f265ce4e548>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f8c8580ce08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f8848d7ce08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fcd64de6e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f9178db9e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6ab3aabdc8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fd954be9e88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6dd14c2e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7ff9e37bbe88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f4180f52dc8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fb1f9db1f88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f089489fe08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fd09e229f88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f12d55b34c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fc3992eae08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f5fe9452e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f363f56ce08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7effec5fcd88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6d70914dc8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fd0366b1d88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f648a9f3e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f7b4b25ee08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f3267efae08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7febc9838e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f2f21f09e48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f7fb402fe08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f14c984f548>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6c14b5de88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f46806a1e88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fdc39f1ce08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f9b13328e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f13d7d5edc8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f9d1be79e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f850c64a548>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f040c285e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f120a2b1e48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f9f853b7548>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f3efa32ee08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fa7b9a22448>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fa33efb8f88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fdb71e59e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f137351f488>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f868fc7d4c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f103c67cdc8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fc414a81f88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f245ac64e48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6f54ca1f88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f4137a4fe08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fe295907e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fbc01399e48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f582734ae88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f938001de48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f13b6bc2d88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f368cc83508>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f407bc70e48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fa9a9922e48>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fb0f8468e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fcc1a64cf88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f9e3f242e08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7feb8299df88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f5b20fc7fc8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f4eff798f88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fa9d50a9d88>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6efa07ae08>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f919db43e48>)
  Cells: 11568
  Connections: 2208855 (190.95 per cell)
  Synaptic contacts: 14985541 (1295.43 per cell)
Plotting 2D representation of network cell locations and connections...
Plotting connectivity matrix...
  Done; plotting time = 6426.09 s

Total time = 8154.49 s

End time:  2021-06-29 18:46:33.843853
Plotting connectivity matrix...
Saving figure data as ../data/v1_batch6/v1_batch6_0_0_pop_numConns_matrix.json ... 
